export const authConstant = {
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
  USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  AUTO_USER_LOGIN_SUCCESS: 'AUTO_USER_LOGIN_SUCCESS',
}

export const linkAPI = {
  LINK: process.env.REACT_APP_LINK_API,
}

export const requestMethod = {
  GET: 'GET', POST: 'POST', PUT: 'PUT', PATCH: 'PATCH', DELETE: 'DELETE'
}

export const axiosConstant = {
  AXIOS_PUT_LOADING: 'AXIOS_PUT_LOADING',
  AXIOS_POP_LOADING: 'AXIOS_POP_LOADING',
  AXIOS_CLOSE_POPUP_ERROR: 'AXIOS_CLOSE_POPUP_ERROR',
  AXIOS_OPEN_POPUP_ERROR: 'AXIOS_OPEN_POPUP_ERROR',
  AXIOS_CLEAR_MESSAGE_ERROR: 'AXIOS_CLEAR_MESSAGE_ERROR',
}

export const requestStatus = {
  SUCCESS: [200, 201],
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  SERVER_ERROR: 500
}